name: bitcoin_price_pulse
description: "cryptocurrency app for viewing bitcoin price"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
#  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1
  freezed_annotation: ^2.4.1
  go_router: ^13.2.4
  get_it: ^7.7.0
  injectable_generator: ^2.6.1
  logger: ^2.2.0
  meta: ^1.11.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  injectable: ^2.4.1
  device_info_plus: ^10.1.0
  intl: ^0.18.1
  dotted_border: ^2.1.0
  dartz: ^0.10.1
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  flutter_bloc: ^8.1.5
  flutter_spinkit: ^5.2.1
  pretty_dio_logger: ^1.3.1
  syncfusion_flutter_gauges: ^25.1.40
  google_fonts: ^6.2.1
  fl_chart: ^0.67.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  freezed: ^2.5.1
  json_serializable: ^6.7.1
  injectable_generator: ^2.6.1
#  Add in next version
#  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
